# Generated by Django 4.1.3 on 2022-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('nombre3', models.CharField(max_length=50)),
                ('dni1', models.IntegerField()),
                ('dni2', models.IntegerField()),
                ('dni3', models.IntegerField()),
                ('nacimiento1', models.DateField()),
                ('nacimiento2', models.DateField()),
                ('nacimiento3', models.DateField()),
            ],
        ),
    ]
